spring:
  application:
    name: mall-admin
  profiles:
    active: dev
  config:
    import: classpath:codegen.yml

server:
  port: 8999
  servlet:
    encoding:
      charset: UTF-8

# 读取pom.xml
project:
  version: @project.version@